name = "laquila-partners"
main = ".open-next/worker.js"
compatibility_date = "2026-04-20"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[routes]]
pattern = "partners.laquilamarketing.com.br"
custom_domain = true
